### ISSUE TITLE
i3bar-xbm-icons.patch no longer works with i3 v4.12

### ISSUE THREAD

**Issue by chilicuil** [ashinkarov/i3-extras#31]
Hello,

I don't expect anyone to work on this, just wanted to point out than the [latest i3 release](https://i3wm.org/downloads/RELEASE-NOTES-4.12.txt) breaks the specified patch.

It seems like this time it will require a fair amount of work to get in form, my attempt to compile i3 with this patch applied fails with the following errors:

```
i3bar/src/xcb.c: In function 'draw_statusline':
i3bar/src/xcb.c:299:17: error: incompatible types when initializing type 'unsigned int' using type 'color_t'
i3bar/src/xcb.c:300:47: error: 'statusline_ctx' undeclared (first use in this function)
i3bar/src/xcb.c:300:47: note: each undeclared identifier is reported only once for each function it appears in
i3bar/src/xcb.c:300:17: warning: passing argument 2 of 'xcb_change_gc' makes integer from pointer without a cast [enabled by default]
/usr/include/xcb/xproto.h:11675:1: note: expected 'xcb_gcontext_t' but argument is of type 'uint32_t *'
i3bar/src/xcb.c:302:17: error: incompatible types when initializing type 'unsigned int' using type 'color_t'
i3bar/src/xcb.c:302:17: error: incompatible types when initializing type 'unsigned int' using type 'color_t'
i3bar/src/xcb.c:303:17: warning: passing argument 2 of 'xcb_change_gc' makes integer from pointer without a cast [enabled by default]
/usr/include/xcb/xproto.h:11675:1: note: expected 'xcb_gcontext_t' but argument is of type 'uint32_t *'
i3bar/src/xcb.c:306:34: error: 'statusline_pm' undeclared (first use in this function)
i3bar/src/xcb.c:307:28: warning: passing argument 2 of 'xcb_image_put' makes integer from pointer without a cast [enabled by default]
/usr/include/xcb/xcb_image.h:347:1: note: expected 'xcb_drawable_t' but argument is of type 'uint32_t *'
i3bar/src/xcb.c:307:28: warning: passing argument 3 of 'xcb_image_put' makes integer from pointer without a cast [enabled by default]
/usr/include/xcb/xcb_image.h:347:1: note: expected 'xcb_gcontext_t' but argument is of type 'uint32_t *'
i3bar/src/xcb.c: In function 'draw_bars':
i3bar/src/xcb.c:2080:17: error: 'block' undeclared (first use in this function)
i3bar/src/xcb.c:2080:22: error: request for member 'icon' in something not a structure or union
i3bar/src/xcb.c:2081:56: error: request for member 'icon' in something not a structure or union
i3bar/src/xcb.c:2081:62: error: request for member 'width' in something not a structure or union
i3bar/src/xcb.c:2081:48: warning: assignment makes integer from pointer without a cast [enabled by default]
make[2]: *** [i3bar/src/xcb.o] Error 1
make[2]: Leaving directory `/tmp/buildd/i3-wm-4.10.1'
make[1]: *** [override_dh_auto_build] Error 2
make[1]: Leaving directory `/tmp/buildd/i3-wm-4.10.1'
make: *** [build-stamp] Error 2
```

Bests

**Comment by ashinkarov** [comment]
Yes, as the last comment indicate, the last version it was rebased on was 4.10; so it is not very surprising.  I will look into that but not earlier than in two weeks.  In the meanwhile, pull requests are welcome :)

**Comment by ashinkarov** [comment]
@chilicuil, can you try out the version from  #33?
It seems to work fine given that you don't use cairo to draw stuff.

**Comment by chilicuil** [comment]
@ashinkarov awesome, it works great on my setup :smile: , how did you know I wasn't using caire?,  is there any disadvantage for not using it?

**Comment by sm4tik** [comment]
https://drive.google.com/file/d/0BxrlY1YYtJPTa1laYWxUYlk5amM/view
New patch is looking good!

**Comment by A-Manning** [comment]
Still broken for 4.15
